//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChaiLvService
{
    using System;
    using System.Collections.Generic;
    
    public partial class loginfo
    {
        public long LogID { get; set; }
        public string LogType { get; set; }
        public string LogDesc { get; set; }
        public int LogUserID { get; set; }
        public string LogUserName { get; set; }
        public System.DateTime LogDate { get; set; }
    }
}
