//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChaiLvService
{
    using System;
    using System.Collections.Generic;
    
    public partial class navigationtree
    {
        public long id { get; set; }
        public string text { get; set; }
        public string state { get; set; }
        public string iconCls { get; set; }
        public string url { get; set; }
        public long nid { get; set; }
        public int RoleID { get; set; }
    }
}
