//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChaiLvService
{
    using System;
    using System.Collections.Generic;
    
    public partial class userinfo
    {
        public long UserID { get; set; }
        public string UserName { get; set; }
        public string UserUint { get; set; }
        public string UserDepartment { get; set; }
        public string UserPwd { get; set; }
        public string UserRole { get; set; }
        public string UserStatus { get; set; }
    }
}
